"""
Target configuration management.

Loads/saves YAML target profiles and builds TargetConfig objects.
"""

from __future__ import annotations

import yaml
from pathlib import Path
from typing import Optional

from secforge.models.target import TargetConfig, AuthConfig, ScopeConfig, ScanOptions


DEFAULT_PROFILE = """\
# SecForge Target Profile
# Generated by: secforge config init

target:
  url: https://api.example.com
  name: "My API"

auth:
  type: none        # Options: none | bearer | api_key | basic
  # token: "eyJhbGci..."         # For bearer
  # header: "X-API-Key"          # For api_key (default: X-API-Key)
  # value: "sk-live-..."         # For api_key
  # username: "admin"            # For basic
  # password: "secret"           # For basic

scope:
  authorized: false
  acknowledged_by: ""            # Your name — required before scanning
  date: ""                       # YYYY-MM-DD
  notes: ""                      # e.g. "Staging environment, authorized by CTO"

headers:
  # Additional headers sent with every request
  # Accept-Language: "en-US"

options:
  timeout: 30
  rate_limit: 10     # Max requests per second
  follow_redirects: true
  verify_ssl: true
  user_agent: "SecForge/0.1 (authorized-pentest)"
"""


def load_target(path: str | Path) -> TargetConfig:
    """Load a YAML target profile and return a TargetConfig."""
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(f"Target profile not found: {p}")

    with p.open() as f:
        raw = yaml.safe_load(f)

    # Support both flat and nested formats
    target_data = raw.get("target", raw)
    auth_data = raw.get("auth", {})
    scope_data = raw.get("scope", {})
    headers = raw.get("headers") or {}
    options_data = raw.get("options", {})

    return TargetConfig(
        url=target_data.get("url", ""),
        name=target_data.get("name", ""),
        auth=AuthConfig(**{k: v for k, v in auth_data.items() if v is not None and v != ""}),
        scope=ScopeConfig(**{k: v for k, v in scope_data.items() if v is not None and v != ""}),
        headers=headers if isinstance(headers, dict) else {},
        options=ScanOptions(**{k: v for k, v in options_data.items() if v is not None}),
    )


def load_target_from_url(url: str) -> TargetConfig:
    """Build a minimal TargetConfig from just a URL (no profile file)."""
    return TargetConfig(url=url, name=url)


def save_profile(path: str | Path, content: str = DEFAULT_PROFILE) -> None:
    """Write a default profile template to disk."""
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content)
